name: DB_updates

on: workflow_dispatch
jobs:
  Update_database:
      permissions: 
        id-token: write   # This is required for requesting the JWT
        contents: read
      runs-on: windows-latest 

      steps:
      - name : checking out the repository
        uses: actions/checkout@v3
          
      - name: Download_files_from_SFTP
        run: |
          Set-ExecutionPolicy RemoteSigned -Force
          Set-ExecutionPolicy Unrestricted -Force
          Install-Module SFTPCmdlets -Force
          Import-Module SFTPCmdlets 
          Install-Module WinSCP -Force -AllowClobber
          Import-Module WinSCP
