name: DB_updates

on: workflow_dispatch
jobs:
  Update_database:
      permissions: 
        id-token: write   # This is required for requesting the JWT
        contents: read
      runs-on: windows-latest 

      steps:
      - name : checking out the repository
        uses: actions/checkout@v3
          
      - name: Download_files_from_SFTP
        run: |
            Install-Module -Name WinSCP

          #Start-Process -FilePath "C:\Winscp\WinSCP-5.19.3-Setup.exe" -ArgumentList "/VERYSILENT /NORESTART" -Wait
          #Remove-Item "WinSCP-5.19.3-Setup.exe"
